services:
  - type: web
    name: superdad-video-n8n
    runtime: docker
    plan: free

    envVars:
      - key: PORT
        value: 5678

      - key: N8N_PORT
        value: 5678

      - key: NODES_EXCLUDE
        value: "[]"

      - key: N8N_RESTRICT_FILE_ACCESS_TO
        value: /automation

      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata

      - key: TZ
        value: Asia/Kolkata

      - key: N8N_PROTOCOL
        value: https

      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: superdad-video-n8n-db
          property: database

      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: superdad-video-n8n-db
          property: host

      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: superdad-video-n8n-db
          property: port

      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: superdad-video-n8n-db
          property: user

      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: superdad-video-n8n-db
          property: password

      - key: N8N_DIAGNOSTICS_ENABLED
        value: false

      - key: N8N_PERSONALIZATION_ENABLED
        value: false

      - key: EXECUTIONS_DATA_PRUNE
        value: true

      - key: EXECUTIONS_DATA_MAX_AGE
        value: 168

      - key: N8N_PAYLOAD_SIZE_MAX
        value: 500

      - key: N8N_FORMDATA_FILE_SIZE_MAX
        value: 500

databases:
  - name: superdad-video-n8n-db
    plan: free
